name: Monitor
on:
  schedule:
    # */5 表示每 5 分钟运行一次（达到 GitHub 允许的最高频率极限）
    - cron: '*/5 * * * *' 
  workflow_dispatch:    

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - run: pip install requests
      - run: python cs2_monitor.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update price data"
          file_pattern: "advanced_data.json"
